language: node_js
node_js:
  - '6'
sudo: false
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version
install:
  - npm install
  - bower install
script:
  - npm test
before_deploy:
  - ember build -prod
env:
  - SURGE_TOKEN=bb46b98b194e39d8df028cbe25213968 SURGE_LOGIN=nick.felicelli@gmail.com
deploy:
  provider: surge
  project: ./dist/
  domain: pickems.surge.sh
